// Code generated by Kitex v0.4.4. DO NOT EDIT.

package messageservice

import (
	"context"
	relation "github.com/ClubWeGo/relationmicro/kitex_gen/relation"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return messageServiceServiceInfo
}

var messageServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "MessageService"
	handlerType := (*relation.MessageService)(nil)
	methods := map[string]kitex.MethodInfo{
		"GetAllMessageMethod": kitex.NewMethodInfo(getAllMessageMethodHandler, newMessageServiceGetAllMessageMethodArgs, newMessageServiceGetAllMessageMethodResult, false),
		"SendMessageMethod":   kitex.NewMethodInfo(sendMessageMethodHandler, newMessageServiceSendMessageMethodArgs, newMessageServiceSendMessageMethodResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "relation",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func getAllMessageMethodHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*relation.MessageServiceGetAllMessageMethodArgs)
	realResult := result.(*relation.MessageServiceGetAllMessageMethodResult)
	success, err := handler.(relation.MessageService).GetAllMessageMethod(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMessageServiceGetAllMessageMethodArgs() interface{} {
	return relation.NewMessageServiceGetAllMessageMethodArgs()
}

func newMessageServiceGetAllMessageMethodResult() interface{} {
	return relation.NewMessageServiceGetAllMessageMethodResult()
}

func sendMessageMethodHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*relation.MessageServiceSendMessageMethodArgs)
	realResult := result.(*relation.MessageServiceSendMessageMethodResult)
	success, err := handler.(relation.MessageService).SendMessageMethod(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMessageServiceSendMessageMethodArgs() interface{} {
	return relation.NewMessageServiceSendMessageMethodArgs()
}

func newMessageServiceSendMessageMethodResult() interface{} {
	return relation.NewMessageServiceSendMessageMethodResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetAllMessageMethod(ctx context.Context, request *relation.GetAllMessageReq) (r *relation.GetAllMessageResp, err error) {
	var _args relation.MessageServiceGetAllMessageMethodArgs
	_args.Request = request
	var _result relation.MessageServiceGetAllMessageMethodResult
	if err = p.c.Call(ctx, "GetAllMessageMethod", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SendMessageMethod(ctx context.Context, request *relation.SendMessageReq) (r *relation.SendMessageResp, err error) {
	var _args relation.MessageServiceSendMessageMethodArgs
	_args.Request = request
	var _result relation.MessageServiceSendMessageMethodResult
	if err = p.c.Call(ctx, "SendMessageMethod", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
