// Code generated by Kitex v0.4.4. DO NOT EDIT.

package combineservice

import (
	"context"
	relation "github.com/ClubWeGo/relationmicro/kitex_gen/relation"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ActionMethod(ctx context.Context, request *relation.ActionReq, callOptions ...callopt.Option) (r *relation.ActionResp, err error)
	GetFollowAndFollowerMethod(ctx context.Context, request *relation.GetFollowAndFollowerReq, callOptions ...callopt.Option) (r *relation.GetFollowAndFollowerResp, err error)
	GetFollowListReqMethod(ctx context.Context, request *relation.GetFollowListReq, callOptions ...callopt.Option) (r *relation.GetFollowListResp, err error)
	GetFollowerListMethod(ctx context.Context, request *relation.GetFollowerListReq, callOptions ...callopt.Option) (r *relation.GetFollowerListResp, err error)
	GetAllMessageMethod(ctx context.Context, request *relation.GetAllMessageReq, callOptions ...callopt.Option) (r *relation.GetAllMessageResp, err error)
	SendMessageMethod(ctx context.Context, request *relation.SendMessageReq, callOptions ...callopt.Option) (r *relation.SendMessageResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCombineServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCombineServiceClient struct {
	*kClient
}

func (p *kCombineServiceClient) ActionMethod(ctx context.Context, request *relation.ActionReq, callOptions ...callopt.Option) (r *relation.ActionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ActionMethod(ctx, request)
}

func (p *kCombineServiceClient) GetFollowAndFollowerMethod(ctx context.Context, request *relation.GetFollowAndFollowerReq, callOptions ...callopt.Option) (r *relation.GetFollowAndFollowerResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFollowAndFollowerMethod(ctx, request)
}

func (p *kCombineServiceClient) GetFollowListReqMethod(ctx context.Context, request *relation.GetFollowListReq, callOptions ...callopt.Option) (r *relation.GetFollowListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFollowListReqMethod(ctx, request)
}

func (p *kCombineServiceClient) GetFollowerListMethod(ctx context.Context, request *relation.GetFollowerListReq, callOptions ...callopt.Option) (r *relation.GetFollowerListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFollowerListMethod(ctx, request)
}

func (p *kCombineServiceClient) GetAllMessageMethod(ctx context.Context, request *relation.GetAllMessageReq, callOptions ...callopt.Option) (r *relation.GetAllMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAllMessageMethod(ctx, request)
}

func (p *kCombineServiceClient) SendMessageMethod(ctx context.Context, request *relation.SendMessageReq, callOptions ...callopt.Option) (r *relation.SendMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendMessageMethod(ctx, request)
}
